### ISSUE TITLE
grafana

### ISSUE THREAD

**Issue by madhavi2491** [ajeje93/grafana-mongodb-docker#1]
i am unable to run docker-compose file can you please let me know.

**Comment by ajeje93** [comment]
Hi, can you share a little more? Do you have any errors in particular?

**Comment by ajeje93** [comment]
I did some updates, try to checkout the repo again and see if it works now. Be careful to set LF line endings in the custom-run.sh file (otherwise it will not work).

EDIT: I also optimized the nodejs installation (nodejs is required for the plugin to work) and fixed the actions 

EDIT2: the commits (I forgot to link them to the issue) are 3b88bacff21d0366f41d3b82beeb6c5f50b218a1 164c47a1b0d6cdae8c0fb684fcf13e5d1dad1a2c 49a427d4beb01c268e5a65d55a285ce2b568e8ac

**Comment by madhavi2491** [comment]
Hi,
  I was able to run compose file now but i had a doubt how can i know that
mongodb plugin is installed or not. I am seeing mongodb as unsigned in
grafana. Please can you help i need mongodb plugin. In my project i am
using mongodb and grafana.

**Comment by ajeje93** [comment]
Hi, it is correct that you see the MongoDB plugin installed as unsigned because it is not an official plugin (https://github.com/JamesOsgood/mongodb-grafana) as stated in the readme file of my repo. For all the instructions to use the MongoDB plugin you can refer to the previous link.
The plugin is composed of two parts:
- the grafana plugin itself
- a nodejs application that runs in the container together with grafana on port 3333 (localhost:3333) that acts as a proxy to MongoDB.

The official plugin exists but it is not free (https://grafana.com/grafana/plugins/grafana-mongodb-datasource/).

**Comment by madhavi2491** [comment]
yes i tried to use (https://github.com/JamesOsgood/mongodb-grafana) this as well. But i had a doubt in that repo. I have to run  grafana and copy (mongodb-grafana) repo into my grafana container. how to run only i was not getting

**Comment by ajeje93** [comment]
The goal of my repo is to copy that repo into the container and running the plugin. In fact as you saw the plugin it is installed inside grafana when you start it. So the part of installing the plugin is already done.

The usage of the plugin is well explained in JamesOsgood repo in the example section of its readme file (https://github.com/JamesOsgood/mongodb-grafana#examples).

In the specific case of the container of my repo, you should set http://localhost:3333 in the HTTP settings when creating the data source.

**Comment by madhavi2491** [comment]
Hi,
   Rightnow i am to login into grafana and it is listining to port 3333.
But how can i see mango db is installed or not in grafana

**Comment by ajeje93** [comment]
Hi, I did some more tests and the plugin installs correctly on Grafana 8 but then I noticed that I am not able to select it for a new datasource. I downgraded Grafana to version 7 and tested it and it working on that version. For a full working example you can check my other repo (https://github.com/ajeje93/speedtest-to-mongodb). You can find all the instructions in the readme file of that repo.

**Comment by madhavi2491** [comment]
Hi,
 thanks its working now.I will you another repo also for mongodb
installation.Once again thanks for your help on this issue.
