### ISSUE TITLE
Times out for mongodb://localhost:27017

### ISSUE THREAD

**Issue by samleeney** [ajeje93/grafana-mongodb-docker#5]
Great implementation, works perfectly for the example server and other remote servers

I can't get it to connect to the standard 'mongodb://localhost:27017/', however. I'm guessing this is to do with the proxy server being blocked by some firewall? Any ideas how I might go about fixing.

Returns `Failed to fetch' on browser and `Gateway timeout' on server.

This is quite probably a user error rather than a bug!

**Comment by ajeje93** [comment]
Hi, the container does not contain a MongoDB instance. It's Grafana with the open source plugin for MongoDB. 

So you should always have a container with MongoDB running or another external instance. An example would be something like [this](https://github.com/ajeje93/speedtest-to-mongodb/blob/master/docker-compose.full-stack.yml#L24)  where you can see that there is a container named `mongodb` that the hostname that you use in the connection string.

If you want to use the MongoDB instance installed on your machine (localhost) you should use the IP of your machine inside the docker network because localhost points to the container itself and not to your PC. 

You can try something like [this](https://stackoverflow.com/a/45002996) where you use `host.docker.internal` to point to the IP of the host machine.

Hope that helps!

**Comment by samleeney** [comment]
> You can try something like [this](https://stackoverflow.com/a/45002996) where you use host.docker.internal to point to the IP of the host machine.

This should work - but I can't seem to implement it in this case. Any chance you could send a version of the docker-compose file with it included? Apologies but I'm completely new to docker.

Edit: I have tried building outside of docker and the same error occurs.

**Comment by ajeje93** [comment]
Sorry for the super late response. The docker-compose file should look something like this:

```yaml
version: "3"
services:
  prod:
    image: ajeje93/grafana-mongodb:latest
    restart: always
    volumes:
     - ./data:/var/lib/grafana
     - /var/lib/grafana/plugins
    ports:
     - 3000:3000
```

Then when you configure the plugin you should use `mongodb://host.docker.internal:27017` in the MongoDB URL to point to the MongoDB instance installed on your PC. Anyways for the plugin configuration you should refer to the plugin repo https://github.com/SiemaApplications/mongodb-grafana#readme

**Comment by nmcusa** [comment]
Me too lol `Bad Gateway`
